# Prétraitement des données
https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing

In [23]:
# Importer les librairies

import numpy as np
import matplotlib.pyplot as plt
import pandas as pnd

# Importer le dataset

In [74]:
df = pnd.read_csv('Datas/Data.csv')
df.head(11)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [75]:
df = df.dropna()


In [76]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [78]:
df.Purchased = (df['Purchased'] == 'Yes').astype('int64')

In [79]:
df

Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
5   France  35.0  58000.0          1
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

# Gérer les données manquantes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [80]:
X = df.iloc[:, :-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['France', 35.0, 58000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [81]:
y = df.iloc[:, 3].values
y

array([0, 1, 0, 0, 1, 1, 0, 1])

# Gérer les variables catégoriques

Et comme nous pouvons le voir, cet ensemble de données contient une colonne avec des catégories "France Espagne ou Allemagne".<br>
Les variables catégoriques et on va commencer par expliquer pourquoi on doit s'en occuper, la raison est très simple, si on va dans notre dataset, on remarque qu'on a effectivement des variables catégoriques.<br>  

Vous l'avez deviné, il s'agit des variables country, le pays, et Purchased  qui dit si le client a oui ou non acheter. Le produit. <br>

In [42]:
df['Country'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [82]:
df

Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
5   France  35.0  58000.0          1
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [96]:
df.pivot(index=['0', '1','2','3','4','5','6','7','8','9'], columns=['Age','Salary','France','Spain','Germany'], values='Country')

KeyError: 0

In [43]:
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [44]:
# Labelencoder_X = LabelEncoder()

In [45]:
# X[:,0] = Labelencoder_X.fit_transform(X[:,0])

In [46]:
# X[:,0]

array([0, 2, 1, 2, 0, 0, 1, 0], dtype=object)

In [48]:
# onehotencoder = OneHotEncoder()


In [49]:
# X = onehotencoder.fit_transform(X).toarray()

In [67]:
# X[:,5]

array([0., 0., 0., 0., 1., 0., 0., 0.])

# Diviser le dataset entre le Training set et le Test set